### PR TITLE
Add Intel Indicators example

### PR DESCRIPTION
**Pull request by makr11st**
This adds a new example, Query Intel Indicators

### CODE REVIEW

**Comment by redhatrises** [comment]
@makr11st there are a couple of misspelled words that are being flagged. See https://github.com/CrowdStrike/rusty-falcon/pull/100/files

**Comment by mikemadden42** [comment]
@makr11st Any thought on why this check is failing?  I think I was seeing it fail some on my fork too.

- checks / Block fixup commits (pull_request)

**Comment by makr11st** [comment]
> @makr11st Any thought on why this check is failing?  I think I was seeing it fail some on my fork too.
> 
> - checks / Block fixup commits (pull_request)

I made a fixup commit for visibility, I'll squash it before merge or maybe I should just keep it as a separate?

**Review by mikemadden42 — APPROVED** [review]
Looks good to me.

**Comment by redhatrises** [comment]
> > @makr11st Any thought on why this check is failing?  I think I was seeing it fail some on my fork too.
> > 
> > * checks / Block fixup commits (pull_request)
> 
> I made a fixup commit for visibility, I'll squash it before merge or maybe I should just keep it as a separate?

Go ahead and squash it so that CICD will pass.

**Pull request merged**
